_commit: v1.11.1
_src_path: /Users/crthomas/code/charlesthomas/homelab-template
additionalResources: automations.yaml
backups: false
helm: false
homepageDescription: Home Automator
homepageEnabled: true
homepageGroup: Home Automation
homepageIcon: home-assistant
homepageName: Home Assistant
ingClass: nginx-internal
ingCname: ''
ingExtraAnnotations: ''
ingHost: ass.crt.house
ingName: home-assistant
ingPathType: Prefix
ingWebSockets: true
ingress: true
labels: |-
  app.kubernetes.io/name: home-assistant
  app.kubernetes.io/instance: home-assistant
name: home-assistant
namespace: home-assistant
pvc: true
pvcAccessMode: ReadWriteOnce
pvcName: home-assistant
pvcSize: 50Gi
pvcStorageClass: longhorn
reloader: true
resources:
- configmaps.yaml
- deployments.yaml
- external-secrets.yaml
- ingresses.yaml
- pvcs.yaml
- services.yaml
service: true
serviceAccount: false
svcName: home-assistant
svcPortName: http
svcPortNum: 8123
svcProtocol: TCP
svcSelector: |-
  app.kubernetes.io/name: home-assistant
  app.kubernetes.io/instance: home-assistant
svcTargetPort: http
svcType: ClusterIP
upstreamURL: https://home-assistant.io
url: https://github.com/charlesthomas/homelab-home-assistant
