---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-assistant

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-home-assistant
commonLabels:
  app: home-assistant
  app.kubernetes.io/name: home-assistant
  app.kubernetes.io/instance: home-assistant

resources:
- resources/configmaps.yaml
- resources/deployments.yaml
- resources/external-secrets.yaml
- resources/ingresses.yaml
- resources/namespaces.yaml
- resources/pvcs.yaml
- resources/services.yaml
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: all
      namespace: home-assistant
      annotations:
        reloader.stakater.com/auto: "true"
  target:
    kind: Deployment
