---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-assistant

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-home-assistant
commonLabels:
  app.kubernetes.io/name: home-assistant
  app.kubernetes.io/instance: home-assistant

images:
  - name: home-assistant
    newName: ghcr.io/home-assistant/home-assistant
    newTag: 2025.6.1

resources:
- resources/automations.yaml
- resources/configmaps.yaml
- resources/dashboards.yaml
- resources/deployments.yaml
- resources/external-secrets.yaml
- resources/ingresses.yaml
- resources/namespaces.yaml
- resources/pvcs.yaml
- resources/services.yaml
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: all
      namespace: home-assistant
      annotations:
        reloader.stakater.com/auto: "true"
  target:
    kind: Deployment
- patch: |-
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: home-assistant
      namespace: home-assistant
      annotations:
        gethomepage.dev/href: https://ass.crt.house
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: Home Automator
        gethomepage.dev/group: Home Automation
        gethomepage.dev/icon: home-assistant
        gethomepage.dev/name: Home Assistant
        gethomepage.dev/pod-selector: ""
  target:
    kind: Ingress
