---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configuration
  namespace: home-assistant
data:
  configuration.yaml: |
    default_config:

    automation: !include automations.yaml

    dashboards: !include dashboards.yaml

    homeassistant:
      name: 337
      latitude: !env_var LATITUDE
      longitude: !env_var LONGITUDE
      elevation: 709
      unit_system: imperial
      time_zone: America/Detroit

    http:
      use_x_forwarded_for: true
      trusted_proxies:
      - 192.168.1.0/24
      - 10.42.0.0/16

    adaptive_lighting:
      - name: "ct office"
        min_brightness: 100
        max_brightness: 100
        min_color_temp: 2500
        max_color_temp: 6500
        lights: [
          "light.ct_office_lamp_left",
          "light.ct_office_lamp_right",
        ]
      - name: "living room"
        min_brightness: 100
        max_brightness: 100
        min_color_temp: 2500
        max_color_temp: 6500
        sleep_brightness: 35
        sleep_color_temp: 2500
        sleep_rgb_or_color_temp: color_temp
        lights: [
          "light.lr_left_front",
          "light.lr_left_rear",
          "light.lr_right_front",
          "light.lr_right_rear"
        ]
      - name: "ct bedroom"
        min_brightness: 100
        max_brightness: 100
        min_color_temp: 2500
        max_color_temp: 6500
        sleep_brightness: 35
        sleep_rgb_or_color_temp: rgb_color
        sleep_rgb_color: [255, 0, 0]
        lights: [
          "light.ct_br_lamp",
          "light.ct_bath_left",
          "light.ct_bath_center",
          "light.ct_bath_right"
        ]
      - name: "guest bathroom"
        min_brightness: 100
        max_brightness: 100
        min_color_temp: 2500
        max_color_temp: 6500
        sleep_brightness: 35
        sleep_rgb_or_color_temp: rgb_color
        sleep_rgb_color: [255, 0, 0]
        lights: [
          "light.guest_bath_left",
          "light.guest_bath_center",
          "light.guest_bath_right"
        ]
