---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ass.crt.house
    nginx.org/websocket-services: home-assistant
    gethomepage.dev/href: https://ass.crt.house
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Home Automator
    gethomepage.dev/group: Home Automation
    gethomepage.dev/icon: home-assistant
    gethomepage.dev/name: Home Assistant
    gethomepage.dev/pod-selector: ""
spec:
  ingressClassName: nginx-crt-house
  rules:
    - host: "ass.crt.house"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: home-assistant
                port:
                  number: 8123
  tls:
    - hosts:
      - ass.crt.house
