#!/bin/bash
if [ $(git status --porcelain automations/ | wc -l) -gt 0 ]; then
    ./bin/generate-automations.bash
    git add resources/automations.yaml
fi

if [ $(git status --porcelain dashboards/ | wc -l) -gt 0 ]; then
    ./bin/generate-dashboards.bash
    git add resources/dashboards.yaml
fi
