mode: single
description: "CT Bedroom Nightstand Lamp Button"
triggers:
  - domain: mqtt
    device_id: 4538583a1da24852d0d076fe29b6fcfe
    type: action
    subtype: single
    trigger: device
conditions: []
actions:
  - type: toggle
    device_id: 86947dc3993b59bc2a428d4fd8b90fde
    entity_id: a7b7086e644289db071ea71a9a9fc2a2
    domain: light
  - type: turn_off
    device_id: cf13b868bb8a1a584e068d0d53696471
    entity_id: d7ab22d757c625e844ddd57ed7844b7a
    domain: light
  - type: turn_off
    device_id: 05db9b5d8b33e6d69d61e0c3f10097d2
    entity_id: cdf1e1e3d57d631d90df24dd66f10f62
    domain: light
  - type: turn_off
    device_id: 4251f1ff975d7308138c51e433cb3c20
    entity_id: 1e22633599370136c48f4612f13cbf74
    domain: light
