alias: CT Bedroom Lights Button
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.ct_bedroom_button_action
    attribute: action
    to: single
condition: []
action:
  - type: toggle
    device_id: 86947dc3993b59bc2a428d4fd8b90fde
    entity_id: a7b7086e644289db071ea71a9a9fc2a2
    domain: light
mode: single
