alias: CT Bath Motion Off
description: ""
trigger:
  - type: no_motion
    platform: device
    device_id: eb8c523f2bba8c1e78886b92ca19c3b7
    entity_id: d1302ff56bd05d0cb96631d4471db6e0
    domain: binary_sensor
    for:
      hours: 0
      minutes: 1
      seconds: 0
action:
  - type: turn_off
    device_id: cf13b868bb8a1a584e068d0d53696471
    entity_id: d7ab22d757c625e844ddd57ed7844b7a
    domain: light
  - type: turn_off
    device_id: 4251f1ff975d7308138c51e433cb3c20
    entity_id: 1e22633599370136c48f4612f13cbf74
    domain: light
  - type: turn_off
    device_id: 05db9b5d8b33e6d69d61e0c3f10097d2
    entity_id: cdf1e1e3d57d631d90df24dd66f10f62
    domain: light
mode: single
