alias: CT Bath Humidity High Fan On
description: ""
trigger:
  - platform: template
    value_template: >-
      {{ (states.sensor.acurite_15182_ct_bath_h.state | float - states.sensor.acurite_11300_laundry_room_h.state | float) > 5 }}
condition:
  - condition: state
    entity_id: switch.adaptive_lighting_sleep_mode_ct_bedroom
    state: "off"
action:
  - type: turn_on
    device_id: 9a42216157a4697779238535b9f655f9
    entity_id: 56ff874adba8da9c0b533aa74f230091
    domain: switch
mode: single

