alias: CT Bath Lights Button
description: ""
trigger:
  - platform: device
    domain: mqtt
    device_id: 79c19a3bf18b35816118b4afff3a7da3
    type: action
    subtype: single
    discovery_id: 0xa4c138a5359f14ac action_single
condition: []
action:
  - type: toggle
    device_id: cf13b868bb8a1a584e068d0d53696471
    entity_id: d7ab22d757c625e844ddd57ed7844b7a
    domain: light
  - type: toggle
    device_id: 05db9b5d8b33e6d69d61e0c3f10097d2
    entity_id: cdf1e1e3d57d631d90df24dd66f10f62
    domain: light
  - type: toggle
    device_id: 4251f1ff975d7308138c51e433cb3c20
    entity_id: 1e22633599370136c48f4612f13cbf74
    domain: light
mode: single
