alias: Main Bathroom Dehumidifier Off
description: ""
mode: single
trigger:
  - platform: state
    entity_id:
      - binary_sensor.main_bath_humidity_ok
    to: "on"
condition: []
action:
  - type: turn_off
    device_id: 4bbf14db67657f22f149e563bc8e2b0d
    entity_id: 3f5a11bf349d1a1ca109cfedfadf6527
    domain: switch
  - type: turn_off
    device_id: 9a42216157a4697779238535b9f655f9
    entity_id: 56ff874adba8da9c0b533aa74f230091
    domain: switch
