alias: CT Bath Humidity High Fan On
description: ""
trigger:
  - platform: template
    value_template: >-
      {{ (states.sensor.ct_bath_inside_humidity.state | float -
      states.sensor.ct_bath_outside_humidity.state | float) > 5 | int }}
condition:
  - condition: state
    entity_id: switch.adaptive_lighting_sleep_mode_ct_bedroom
    state: "off"
action:
  - type: turn_on
    device_id: 9a42216157a4697779238535b9f655f9
    entity_id: 56ff874adba8da9c0b533aa74f230091
    domain: switch
mode: single

