alias: CT Office Lights Button
description: ""
mode: single
trigger:
  - platform: device
    domain: mqtt
    device_id: 860e6a173f449a37ab59d2460186b6b6
    type: action
    subtype: single
    discovery_id: 0x28dba7fffe002085 action_single
condition: []
action:
  - type: toggle
    device_id: 1b5cb704a1adfbc34ccdae541a4559c1
    entity_id: 4d81cf020b3b06f5ee3d8eaa45f04ba3
    domain: light
  - type: toggle
    device_id: 5a1a3082e0be230fd3943b7a58675660
    entity_id: 6ca0bbf3d632bf32c6b1002559d06f5c
    domain: light
