alias: Guest Bath Humidity High Fan On
description: ""
mode: single
trigger:
  - platform: template
    value_template: >-
      {{ (states.sensor.guest_bath_inside_humidity.state | float - states.sensor.guest_bath_outside_humidity.state | float) > 5 }}
condition:
  - condition: state
    entity_id: switch.adaptive_lighting_sleep_mode_guest_bathroom
    state: "off"
action:
  - type: turn_on
    device_id: 82a624b807353a788f8805a8a11447ec
    entity_id: 398a9a95e9e25f2f3555f0b123ea340e
    domain: switch
