alias: Guest Bath Dehumidifier Off
description: ""
mode: single
trigger:
  - platform: state
    entity_id:
      - binary_sensor.guest_bath_humidity_ok
    to: "on"
condition: []
action:
  - type: turn_off
    device_id: a35930e3830bebaf8077a5590665e858
    entity_id: 60efa062c449539dfee60ad7b94e35cc
    domain: switch
  - type: turn_off
    device_id: 82a624b807353a788f8805a8a11447ec
    entity_id: 398a9a95e9e25f2f3555f0b123ea340e
    domain: switch
