alias: Guest Bath Lights Button
description: ""
trigger:
  - platform: device
    domain: mqtt
    device_id: 554def67b2a21938292236d4cf566d45
    type: action
    subtype: single
    discovery_id: 0xa4c138b5a6a4eaeb action_single
condition: []
action:
  - type: toggle
    device_id: fa4bba6fd8a65f4809b4478988b7438d
    entity_id: f27e48812678ac93479ec82b9d269433
    domain: light
  - type: toggle
    device_id: bf83e270293f87aed81d5e4803afe4ab
    entity_id: 569bfa5736db521ed3e996132075bc9a
    domain: light
  - type: toggle
    device_id: 12911c98dfa17da0ca1355fddb794804
    entity_id: 05bc316c1cf4b0faa6124d29cfbda14c
    domain: light
mode: single
