alias: Guest Bath Humidity Low Fan Off
description: ""
trigger:
  - platform: template
    value_template: >-
      {{ (states.sensor.acurite_1194_guest_bathroom_h.state | float - states.sensor.acurite_11300_laundry_room_h.state | float) <= 3 }}
condition: []
action:
  - type: turn_off
    device_id: 82a624b807353a788f8805a8a11447ec
    entity_id: 398a9a95e9e25f2f3555f0b123ea340e
    domain: switch
mode: single

