alias: Guest Bath Sleep Mode Schedule Off
description: ""
mode: single
trigger:
  - platform: state
    entity_id:
      - schedule.guest_bathroom_sleep_mode
    to: "off"
condition: []
action:
  - service: switch.turn_off
    target:
      entity_id: switch.adaptive_lighting_sleep_mode_guest_bathroom
    data: {}
