alias: Guest Bath Humidity High Fan On
description: ""
mode: single
trigger:
  - platform: template
    value_template: >-
      {{ (states.sensor.acurite_1194_guest_bathroom_h.state | float -
      states.sensor.acurite_11300_laundry_room_h.state | float) > 6 }}
condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: switch.adaptive_lighting_sleep_mode_guest_bathroom
        state: "off"
      - condition: state
        entity_id: input_boolean.movie_mode
        state: "off"
action:
  - type: turn_on
    device_id: 82a624b807353a788f8805a8a11447ec
    entity_id: 398a9a95e9e25f2f3555f0b123ea340e
    domain: switch
