alias: Guest Bath Dehumidifier On
description: ""
mode: single
trigger:
  - platform: state
    entity_id:
      - binary_sensor.guest_bath_humidity_high
    to: "on"
condition: []
action:
  - type: turn_on
    device_id: a35930e3830bebaf8077a5590665e858
    entity_id: 60efa062c449539dfee60ad7b94e35cc
    domain: switch
  - if:
      - type: is_motion
        condition: device
        device_id: 7614bffd513319c78ea30c606fce4577
        entity_id: 4122434e3e8076342d34299df6472544
        domain: binary_sensor
    then:
      - type: turn_on
        device_id: 82a624b807353a788f8805a8a11447ec
        entity_id: 398a9a95e9e25f2f3555f0b123ea340e
        domain: switch
