alias: Kitchen Motion Off
description: ""
trigger:
  - type: no_motion
    platform: device
    device_id: 016922535828fe99112d2185c9e6d266
    entity_id: b9f661d5f04e35dc33e80fce29908f2c
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 30
condition:
  - condition: state
    entity_id: input_boolean.kitchen_automation
    state: "on"
action:
  - type: turn_off
    device_id: 64cb39541183d46fd5d8f061f93a02e9
    entity_id: a73f4a5455f4e18749c6aab38182339d
    domain: switch
