alias: Pausing Living Room TV Turns Art Lamps On
description: ""
mode: single
trigger:
  - platform: device
    device_id: 9740bbcab565039940bba000fd826456
    domain: media_player
    entity_id: 82ef8ecd276eac8b6467aab84b76b095
    type: paused
    for:
      hours: 0
      minutes: 0
      seconds: 15
  - platform: device
    device_id: 9740bbcab565039940bba000fd826456
    domain: media_player
    entity_id: 82ef8ecd276eac8b6467aab84b76b095
    type: idle
  - platform: device
    device_id: 9740bbcab565039940bba000fd826456
    domain: media_player
    entity_id: 82ef8ecd276eac8b6467aab84b76b095
    type: turned_off
condition:
  - condition: state
    entity_id: schedule.art_lamp_schedule
    state: "on"
action:
  - type: turn_on
    device_id: 8b79e845f6a049c987bd0ce6a5701f0e
    entity_id: 0e1066f63544d20985d05e4da841cd6e
    domain: switch
