alias: Pausing Living Room TV Turns Art Lamps On
description: ""
mode: single
trigger:
  - platform: device
    device_id: 9b8d6246ca553e5e0ef66221c911e516
    domain: media_player
    entity_id: d086e0de65e1090f565195bb4fa2ebf4
    type: paused
    for:
      hours: 0
      minutes: 0
      seconds: 15
  - platform: device
    device_id: 9b8d6246ca553e5e0ef66221c911e516
    domain: media_player
    entity_id: d086e0de65e1090f565195bb4fa2ebf4
    type: idle
  - platform: device
    device_id: 9b8d6246ca553e5e0ef66221c911e516
    domain: media_player
    entity_id: d086e0de65e1090f565195bb4fa2ebf4
    type: turned_off
condition:
  - condition: state
    entity_id: schedule.art_lamp_schedule
    state: "on"
action:
  - type: turn_on
    device_id: 8b79e845f6a049c987bd0ce6a5701f0e
    entity_id: 0e1066f63544d20985d05e4da841cd6e
    domain: switch
