alias: Pausing Living Room TV Turns Art Lamps On
description: ""
mode: single
trigger:
  - platform: state
    entity_id:
      - binary_sensor.living_room_tv_playing
    to: "off"
    for:
      hours: 0
      minutes: 1
      seconds: 0
condition:
  - condition: state
    entity_id: schedule.art_lamp_schedule
    state: "on"
action:
  - type: turn_on
    device_id: 8b79e845f6a049c987bd0ce6a5701f0e
    entity_id: 0e1066f63544d20985d05e4da841cd6e
    domain: switch
