alias: Playing Living Room TV Turns Art Lamps Off
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.living_room_tv_playing
    to: "on"
condition: []
action:
  - type: turn_off
    device_id: 8b79e845f6a049c987bd0ce6a5701f0e
    entity_id: 0e1066f63544d20985d05e4da841cd6e
    domain: switch
mode: single
