alias: Playing Living Room TV Turns Art Lamps Off
description: ""
trigger:
  - platform: device
    device_id: 9b8d6246ca553e5e0ef66221c911e516
    domain: media_player
    entity_id: d086e0de65e1090f565195bb4fa2ebf4
    type: playing
condition: []
action:
  - type: turn_off
    device_id: 8b79e845f6a049c987bd0ce6a5701f0e
    entity_id: 0e1066f63544d20985d05e4da841cd6e
    domain: switch
mode: single
