alias: Playing Living Room TV Turns Art Lamps Off
description: ""
trigger:
  - platform: device
    device_id: 9740bbcab565039940bba000fd826456
    domain: media_player
    entity_id: 82ef8ecd276eac8b6467aab84b76b095
    type: playing
condition: []
action:
  - type: turn_off
    device_id: 8b79e845f6a049c987bd0ce6a5701f0e
    entity_id: 0e1066f63544d20985d05e4da841cd6e
    domain: switch
mode: single
